objects = main.o addition.o subtraction.o multiplication.o division.o

calculator: $(objects)
	cc -o calculator $(objects)

main.o:

addition.o:

subtraction.o:

multiplication.o:

division.o:

clean:
	rm -f sample $(objects)
#	calculator: $(objects)
#		cc -o calculator $(objects)

.PHONY: clean
